config/routes.rb
Rails.application.routes.draw do

  resources :sipocs
  devise_for :users
  devise_scope :user do
	authenticated :user do
  get 'home/index'
  root 'home#index'


  get '/dashboard', to: "dashboard#index"
  get :tool1, to: "dashboard#tool1"
  get :tool2, to: "dashboard#tool2"
  get :nothing, to: "dashboard#nothing"


  get '/sipocs', to: 'sipocs#index'
  get '/sipocs/new', to: 'sipocs#new'
  post '/sipocs', to: 'sipocs#create'
  get '/sipocs/:id/edit', to: 'sipocs#edit'
  patch '/sipocs/:id', to: 'sipocs#update', as: 'update_sipoc' #submission
  get'/sipocs/:id', to: 'sipocs#show', as: 'show_sipoc' #display
  delete '/sipocs/:id', to: 'sipocs#destroy'


  get '/vsms', to: 'vsms#index'
  get '/vsms/new', to: 'vsms#new', as: 'new_vsm'
  post '/vsms/', to: "vsms#create"
  get '/vsms/:id/edit', to: 'vsms#edit', as: 'edit_vsm'
  patch '/vsms/:id', to: 'vsms#update', as: 'update_vsm' #submission
  get'/vsms/:id', to: 'vsms#show', as: 'show_vsm' #display
  delete '/vsms/:id', to: 'vsms#destroy'


  get '/profile', to: "profile#index"

  #resources :vsm #same as commented above

end
	
	unauthenticated do
		root 'home#index', as: :unauthenticated_root
	end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vsm.rb
class Vsm < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true

	validates :file_name, presence: true, length: {minimum: 3, maximum: 20}

	validates :inventory1, presence: true
	validates :processA, presence: true
	validates :resourceA, presence: true
	validates :dataA1, presence: true
	validates :dataA2, presence: true

	validates :dataA3, presence: true
	validates :inventory2, presence: true
	validates :processB, presence: true
	validates :resourceB, presence: true
	validates :dataB1, presence: true

	validates :dataB2, presence: true
	validates :dataB3, presence: true
	validates :inventory3, presence: true
	validates :processC, presence: true
	validates :resourceC, presence: true

	validates :dataC1, presence: true
	validates :dataC2, presence: true
	validates :dataC3, presence: true
	validates :inventory4, presence: true
	validates :processD, presence: true

	validates :resourceD, presence: true
	validates :dataD1, presence: true
	validates :dataD2, presence: true
	validates :dataD3, presence: true
	validates :PLT1, presence: true

	validates :PLT2, presence: true
	validates :PLT3, presence: true
	validates :PLT4, presence: true
	validates :PT1, presence: true
	validates :PT2, presence: true

	validates :PT3, presence: true
end

app/controllers/vsms_controller.rb
class VsmsController < ApplicationController
	def index
		session[:load_part] = 2
  		redirect_to dashboard_path
	end

	def show
		@vsm = Vsm.find(params[:id])
	end

	def new
		@vsm = Vsm.new
	end

	def create
		@vsm = Vsm.new(vsm_params)
		@vsm.user = User.find(1)

		if @vsm.save
			flash[:notice] = "Your VSM has been saved to your profile!"
			redirect_to dashboard_path
		else
			render:new
		end
	end

	def edit
		@vsm = Vsm.find(params[:id])
	end

	def update
		@vsm = Vsm.find(params[:id])
		if @vsm.update(vsm_params)
			flash[:notice] = "Your VSM has been updated successfully!"
			redirect_to profile_path(@vsm)
		else
			render :edit
		end
	end

	def destroy
		@vsm = Vsm.find(params[:id])
  		@vsm.destroy
  		flash[:alert] = "Your VSM has been deleted!"
  		redirect_to profile_path
	end

	private 

		def vsm_params
			params.require(:vsm).permit(:file_name, :inventory1, :processA, :resourceA, :dataA1, :dataA2, :dataA3,
										:inventory2, :processB, :resourceB, :dataB1, :dataB2, :dataB3,
										:inventory3, :processC, :resourceC, :dataC1, :dataC2, :dataC3,
										:inventory4, :processD, :resourceD, :dataD1, :dataD2, :dataD3,
										:PLT1, :PLT2, :PLT3, :PLT4, :PT1, :PT2, :PT3)
		end


end

app/views/vsms/edit.html.erb
<!--
<h1>Load 2</h1>

<%= link_to "Load Part 1", tool1_path %>
-->

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Edit Value Stream Map</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/grid/">
    <%= stylesheet_link_tag "RaulCSS.css"%>
    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.3/examples/grid/grid.css" rel="stylesheet">
  </head>
  <body class="py-4" id="background">
    <nav class="site-header sticky-top py-1">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="/dashboard">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24" focusable="false"><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
        </a>
      </div>
    </nav>
    <div class="container">
<h1 class="text-center">Edit Value Stream Map</h1>
<br>
      <div class="row">
        <div class="col-2 text-center">          
<%= form_for @vsm, :url => update_vsm_path do |f| %>
            <%= f.text_field :file_name, :class=>"form-control"%>
          </div>
        </div>
        
<br>
  <div class="row mb-3 text-center">
    <div class="col"></div>
    <div class="col-4 themed-grid-col"><h5 class="card-header text-center">Production Control</h5></div>
    <div class="col"></div>
  </div>

<br><br>

  <div class="row mb-3 text-center">
    <div class="col-3 themed-grid-col"><h5 class="card-header text-center">Supplier</h5></div>
    <div class="col"></div>
    <div class="col-3 themed-grid-col"><h5 class="card-header text-center">Customer</h5></div>
  </div>
<p class="float-right"><i>Monthly</i></p>


<br>
<p><i>Weekly</i></p>
<img style="height:65px" style="width:65px" <%= image_tag "truck.png"%>
<img style="height:200px" style="width:70px" <%= image_tag "ArrowDown.png"%>


<img class="float-right" style="height:65px" style="width:65px" <%= image_tag "truck.png"%>
<img class="float-right" style="height:200px" style="width:70px" <%= image_tag "ArrowUp.png"%>

<br><br><br>

<div class="float-left" id="up">
        <p>I</p>
</div>


<div class="form-row">
  <div class="form-group">
  <%= f.number_field :inventory1, :class=>"form-control col-6 m1-1 float-left" %>
</div>
</div>


<img style="height:50px" style="width:50px" <%= image_tag "ArrowRight.png"%>
<div class="form-inline">
  <div class="form-group">
    <div class="divider5"></div>
  <%= f.number_field :inventory2, :class=>"form-control col-6 ml-1" %>
</div>
<div class="form-group">
  <div class="divider3"></div>
  <%= f.number_field :inventory3, :class=>"form-control col-6 ml-1" %>
</div>
<div class="form-group">
  <div class="divider3"></div>
  <%= f.number_field :inventory4, :class=>"form-control col-6 ml-1" %>
</div>
</div>

<!---------------------- Processes ------------------------->


  <div class="row mb-3 text-center">

    <div class="col-2 themed-grid-col">
      <h5 class="card-header text-center"><%= f.text_field :processA, :class=>"form-control" %></h5>
      <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text" style="width:127px"><strong><%= f.text_area :resourceA, rows: 5, :class=>"form-control"%></strong></p>
      <p><img class="float-left" style="height:25px" style="width:25px" <%= image_tag "VSMlogo.png"%></p>
      </div>
    </div>


    <div class="col">
      
      <div id="up">
        <p>
        I
        </p>
      </div>
      <img style="height:50px" style="width:50px" <%= image_tag "ArrowRight.png"%>

    </div>

    <div class="col-2 themed-grid-col">
      <h5 class="card-header text-center"><%= f.text_field :processB, :class=>"form-control" %></h5>
      <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text" style="width:127px"><strong><%= f.text_area :resourceB, rows: 5, :class=>"form-control" %></strong></p>
      <p><img class="float-left" style="height:25px" style="width:25px" <%= image_tag "VSMlogo.png"%></p>
      </div>
    </div>


    <div class="col">
      
      <div id="up">
        <p>
        I
        </p>
      </div>
      <img style="height:50px" style="width:50px" <%= image_tag "ArrowRight.png"%>

    </div>


    <div class="col-2  themed-grid-col">
      <h5 class="card-header text-center"><%= f.text_field :processC, :class=>"form-control" %></h5>
      <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text" style="width:127px"><strong><%= f.text_area :resourceC, rows: 5, :class=>"form-control" %></strong></p>
      <p><img class="float-left" style="height:25px" style="width:25px" <%= image_tag "VSMlogo.png"%></p>
      </div>
    </div>


    <div class="col">
      
      <div id="up">
        <p>
        I
        </p>
      </div>
      <img style="height:50px" style="width:50px" <%= image_tag "ArrowRight.png"%>

    </div>


    <div class="col-2  themed-grid-col">
      <h5 class="card-header text-center"><%= f.text_field :processD, :class=>"form-control" %></h5>
      <div class="card-body text-center">
      <h4 class="card-title"></h4>
      <p class="card-text" style="width:127px"><strong><%= f.text_area :resourceD, rows: 5, :class=>"form-control" %></strong></p>
      <p><img class="float-left" style="height:25px" style="width:25px" <%= image_tag "VSMlogo.png"%></p>
      </div>
    </div>

  </div>


<div class="row mb-3 text-center">

    <div class="col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:55px"><%= f.text_field :dataA1, :class=>"form-control form-control form-control-sm ml-1 " %></div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:55px"><%= f.text_field :dataA2, :class=>"form-control form-control form-control-sm ml-1 " %></div>
      <div class="col"></div>
      <div class="col-12  themed-grid-col" style="height:55px"><%= f.text_field :dataA3, :class=>"form-control form-control form-control-sm ml-1 " %></div>
    </div>


    <div class="col"></div>


    <div class="col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:55px"><%= f.text_field :dataB1, :class=>"form-control form-control form-control-sm ml-1 " %></div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:55px"><%= f.text_field :dataB2, :class=>"form-control form-control form-control-sm ml-1 " %></div>
      <div class="col"></div>
      <div class="col-12  themed-grid-col" style="height:55px"><%= f.text_field :dataB3, :class=>"form-control form-control form-control-sm ml-1 " %></div>
    </div>


    <div class="col"></div>


    <div class="col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:55px"><%= f.text_field :dataC1, :class=>"form-control form-control form-control-sm ml-1 " %></div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:55px"><%= f.text_field :dataC2, :class=>"form-control form-control form-control-sm ml-1 " %></div>
      <div class="col"></div>
      <div class="col-12  themed-grid-col" style="height:55px"><%= f.text_field :dataC3, :class=>"form-control form-control form-control-sm ml-1 " %></div>
    </div>


    <div class="col"></div>


    <div class="col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:55px"><%= f.text_field :dataD1, :class=>"form-control form-control form-control-sm ml-1 " %></div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:55px"><%= f.text_field :dataD2, :class=>"form-control form-control form-control-sm ml-1 " %></div>
      <div class="col"></div>
      <div class="col-12  themed-grid-col" style="height:55px"><%= f.text_field :dataD3, :class=>"form-control form-control form-control-sm ml-1 " %></div>
    </div>

</div>    
<br><br>

<!---------------------- Lead Time Ladder ----------------->


<div class="NhorizontalLine"><%= f.number_field :PLT1, :class=>"form-control col-12 ml-1 " %></div>
<div id="NverticalLine"></div>
<div id="NverticalLine" style="left: 262px"></div>
<div class="NhorizontalLine" style="left: 334px"><%= f.number_field :PLT2, :class=>"form-control col-12 ml-1 " %></div>
<div id="NverticalLine" style="left: 334px"></div>
<div id="NverticalLine" style="left: 406px"></div>
<div id="NverticalLine" style="left: 478px"></div>
<div class="NhorizontalLine" style="left: 478px"><%= f.number_field :PLT3, :class=>"form-control col-12 ml-1 " %></div>
<div id="NverticalLine" style="left: 550px"></div>
<div id="NverticalLine" style="left: 622px"></div>


<span style="top: 1513px">
<div class="col-3 themed-grid-col text-center" style="left:600px">
      <h5 class="text-center">Lead Time Ladder</h5>
      
      <div class="col-12  themed-grid-col" style="height:67px">Production Lead Time = # Days</div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:67px">Processing Time = # Hours</div>
    
</div>
</span>


<div class="NBhorizontalLine" style="left: 262px"><%= f.number_field :PT1, :class=>"form-control col-11 ml-1 " %></div>
<div class="NBhorizontalLine" style="left: 406px"><%= f.number_field :PT2, :class=>"form-control col-11 ml-1 " %></div>
<div class="NBhorizontalLine" style="left: 550px"><%= f.number_field :PT3, :class=>"form-control col-11 ml-1 " %></div>


<div class="NhorizontalLine" style="left: 622px"><%= f.number_field :PLT4, :class=>"form-control col-12 ml-1 " %></div>
<br><br>
<center>
<%= f.submit 'Edit VSM', class: "btn btn-success"%>
</center>

<br><br><br><br><br><br><br><br>

<!---------------------------------------------------------->

<!------------------------ YOU ARE HERE ---------------------------------->

<!------------------------------------- Toggle Option ------------------------------------------

<div id="linezone">
<div  style="width: 805px;height: 106px;top:50px;left:50px;">     
            <div id="elem" onmousedown='mydragg.startMoving(this,"linezone",event);' onmouseup='mydragg.stopMoving("linezone");'>
                <div id="vl"> </div>
            </div>
</div>  
</div>

<div class="float-right col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:37px">Data 1</div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:37px">Data 2</div>
    </div>

---------------------------------------------------------------------------------------------------->


<% end %>

</div> <!-- /container -->
</body>
</html>

app/views/vsms/index.html.erb
<h1>Redirect to Dashboard</h1>

app/views/vsms/show.html.erb
<!--
<h1>Load 2</h1>

<%= link_to "Load Part 1", tool1_path %>
-->

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Value Stream Mapping</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/grid/">
    <%= stylesheet_link_tag "RaulCSS.css"%>
    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.3/examples/grid/grid.css" rel="stylesheet">
  </head>
  <body class="py-4" id="background">

    <nav class="site-header sticky-top py-1">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="/">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24" focusable="false"><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
        </a>
      </div>
    </nav>
    <div class="container">

      <div class="row">
        <div class="col text-center">
          <h1>Value Stream Mapping</h1>
            <p class="lead"><%=@vsm.file_name%></p>
            <p>By: <%= @vsm.user.email =%></p>
            
          </div>
        </div>
        
<br>
<img class="float-left" style="height:130px" style="width:70px" <%= image_tag "LeftDownArrow.png"%>
<img class="float-right" style="height:130px" style="width:70px" <%= image_tag "UpLeftArrow.png"%>
  <div class="row mb-3 text-center">
    <div class="col"></div>
    <div class="col-4 themed-grid-col"><h5 class="card-header text-center">Production Control</h5></div>
    <div class="col"></div>
  </div>

<br><br>

  <div class="row mb-3 text-center">
    <div class="col-3 themed-grid-col"><h5 class="card-header text-center">Supplier</h5></div>
    <div class="col"></div>
    <div class="col-3 themed-grid-col"><h5 class="card-header text-center">Customer</h5></div>
  </div>
<p class="float-right"><i>Monthly</i></p>


<br>
<p><i>Weekly</i></p>
<img style="height:65px" style="width:65px" <%= image_tag "truck.png"%>
<img style="height:200px" style="width:70px" <%= image_tag "ArrowDown.png"%>


<img class="float-right" style="height:65px" style="width:65px" <%= image_tag "truck.png"%>
<img class="float-right" style="height:200px" style="width:70px" <%= image_tag "ArrowUp.png"%>

<br><br><br>

<div class="float-left" id="up">
        <p><%=@vsm.inventory1%></p>
</div>
      <img style="height:50px" style="width:50px" <%= image_tag "ArrowRight.png"%>

<br><br>

<!---------------------- Processes ------------------------->

  <div class="row mb-3 text-center">

    <div class="col-2 themed-grid-col">
      <h5 class="card-header text-center"><%=@vsm.processA%></h5>
      <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text"><strong><%=@vsm.resourceA%></strong></p>
      <p><img class="float-left" style="height:25px" style="width:25px" <%= image_tag "VSMlogo.png"%></p>
      </div>
    </div>


    <div class="col">
      
      <div id="up">
        <p>
        <%=@vsm.inventory2%>
        </p>
      </div>
      <img style="height:50px" style="width:50px" <%= image_tag "ArrowRight.png"%>

    </div>

    <div class="col-2 themed-grid-col">
      <h5 class="card-header text-center"><%=@vsm.processB%></h5>
      <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text"><strong><%=@vsm.resourceB%></strong></p>
      <p><img class="float-left" style="height:25px" style="width:25px" <%= image_tag "VSMlogo.png"%></p>
      </div>
    </div>


    <div class="col">
      
      <div id="up">
        <p>
        <%=@vsm.inventory3%>
        </p>
      </div>
      <img style="height:50px" style="width:50px" <%= image_tag "ArrowRight.png"%>

    </div>


    <div class="col-2  themed-grid-col">
      <h5 class="card-header text-center"><%=@vsm.processC%></h5>
      <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text"><strong><%=@vsm.resourceC%></strong></p>
      <p><img class="float-left" style="height:25px" style="width:25px" <%= image_tag "VSMlogo.png"%></p>
      </div>
    </div>


    <div class="col">
      
      <div id="up">
        <p>
        <%=@vsm.inventory4%>
        </p>
      </div>
      <img style="height:50px" style="width:50px" <%= image_tag "ArrowRight.png"%>

    </div>


    <div class="col-2  themed-grid-col">
      <h5 class="card-header text-center"><%=@vsm.processD%></h5>
      <div class="card-body text-center">
      <h4 class="card-title"></h4>
      <p class="card-text"><strong><%=@vsm.resourceD%></strong></p>
      <p><img class="float-left" style="height:25px" style="width:25px" <%= image_tag "VSMlogo.png"%></p>
      </div>
    </div>

  </div>


<div class="row mb-3 text-center">

    <div class="col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:75px"><%=@vsm.dataA1%></div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:75px"><%=@vsm.dataA2%></div>
      <div class="col"></div>
      <div class="col-12  themed-grid-col" style="height:75px"><%=@vsm.dataA3%></div>
    </div>


    <div class="col"></div>


    <div class="col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:75px"><%=@vsm.dataB1%></div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:75px"><%=@vsm.dataB2%></div>
      <div class="col"></div>
      <div class="col-12  themed-grid-col" style="height:75px"><%=@vsm.dataB3%></div>
    </div>


    <div class="col"></div>


    <div class="col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:75px"><%=@vsm.dataC1%></div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:75px"><%=@vsm.dataC2%></div>
      <div class="col"></div>
      <div class="col-12  themed-grid-col" style="height:75px"><%=@vsm.dataC3%></div>
    </div>


    <div class="col"></div>


    <div class="col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:75px"><%=@vsm.dataD1%></div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:75px"><%=@vsm.dataD2%></div>
      <div class="col"></div>
      <div class="col-12  themed-grid-col" style="height:75px"><%=@vsm.dataD3%></div>
    </div>

</div>    
<br><br>

<!---------------------- Lead Time Ladder ----------------->

<div class="NhorizontalLine"><div class="divider1"></div><%=@vsm.PLT1%></div>
<div id="NverticalLine"></div>
<div id="NverticalLine" style="left: 262px"></div>
<div class="NhorizontalLine" style="left: 334px"><div class="divider1"></div><%=@vsm.PLT2%></div>
<div id="NverticalLine" style="left: 334px"></div>
<div id="NverticalLine" style="left: 406px"></div>
<div id="NverticalLine" style="left: 478px"></div>
<div class="NhorizontalLine" style="left: 478px"><div class="divider1"></div><%=@vsm.PLT3%></div>
<div id="NverticalLine" style="left: 550px"></div>
<div id="NverticalLine" style="left: 622px"></div>


<span style="top: 1513px">
<div class="col-3 themed-grid-col text-center" style="left:630px">
      <h5 class="text-center">Lead Time Ladder</h5>
      
      <div class="col-12  themed-grid-col" style="height:67px">Production Lead Time = <%= @vsm.PLT1 + @vsm.PLT2 + @vsm.PLT3 + @vsm.PLT4 %> Days</div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:67px">Processing Time = <%= @vsm.PT1 + @vsm.PT2 + @vsm.PT3 %> Hours</div>
    
</div>
</span>
<div class="NBhorizontalLine" style="left: 262px"><%=@vsm.PT1%></div>
<div class="NBhorizontalLine" style="left: 406px"><%=@vsm.PT2%></div>
<div class="NBhorizontalLine" style="left: 550px"><%=@vsm.PT3%></div>


<div class="NhorizontalLine" style="left: 622px"><div class="divider1"></div><%=@vsm.PLT4%></div>

<br><br><br><br>
<center>
<%= link_to 'New VSM', new_vsm_path, class: "btn btn-primary" %>
<div class="divider"></div>
<%= link_to "Edit VSM", edit_vsm_path(@vsm), class: "btn btn-success" %>
<div class="divider"></div>
<%= link_to 'Delete', show_vsm_path(@vsm), 
                                      method: :delete,
                                      data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<!--<#%= link_to "Delete this VSM", "/vsms/#{@vsm.id}", method: :delete %>-->


</center>

<br><br>

<br><br><br><br><br><br>

<!---------------------------------------------------------->

<!------------------------ YOU ARE HERE ---------------------------------->

<!------------------------------------- Toggle Option ------------------------------------------

<div id="linezone">
<div  style="width: 805px;height: 106px;top:50px;left:50px;">     
            <div id="elem" onmousedown='mydragg.startMoving(this,"linezone",event);' onmouseup='mydragg.stopMoving("linezone");'>
                <div id="vl"> </div>
            </div>
</div>  
</div>

<div class="float-right col-2 themed-grid-col text-center">
      <div class="col-12  themed-grid-col" style="height:37px">Data 1</div>
      <div class="col"></div>
      <div class="col-12 themed-grid-col" style="height:37px">Data 2</div>
    </div>

---------------------------------------------------------------------------------------------------->





</div> <!-- /container -->
</body>
</html>